const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>Math.round(n||0).toLocaleString('vi-VN')+'đ';
const defaults={StandardDays:26,AttendanceBonus:400000,InsuranceRate:.105,UnionRate:.005,NormalOvertimeRate:1.5,SundayDayRate:2,SundayNightRate:2.8,NightExtraRate:.3,NightOvertimeAfter2Rate:2.15,NightExtraHours:6,SundayDefaultHours:11,LeaveAccrualDay:16,LeaveAccrualAmount:1};
const newEmp=()=>({Id:crypto.randomUUID(),Name:'Nhân viên 1',Department:'Cá nhân',Code:'NV01',SalaryBase:8500000,OvertimeBase:7000000,AnnualLeaveBalance:0,LastLeaveAccrualDate:new Date().toISOString()});
let data=JSON.parse(localStorage.getItem('chamcong_data')||'null')||{Employees:[newEmp()],Attendance:[],LeaveAccruals:[],Settings:{...defaults}}; data.Settings={...defaults,...data.Settings};
let current=data.Employees[0], selected=new Date(), calDate=new Date(), month=new Date().getMonth()+1, year=new Date().getFullYear();
const cfg=()=>JSON.parse(localStorage.getItem('github_cfg')||'{}');
function saveLocal(){localStorage.setItem('chamcong_data',JSON.stringify(data)); renderAll()}
function isoDate(d){let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function fmt(d){return new Date(d).toLocaleDateString('vi-VN')}
function typeName(t){return ['Đi làm','Nghỉ phép','Tăng ca','Nghỉ lễ'][+t]||t}
function typeVal(t){return typeof t==='number'?t:{Work:0,PaidLeave:1,OvertimeOnly:2,Holiday:3}[t]??+t}
function shiftVal(s){return s===1||s==='Night'?'Night':'Day'}
function paid(r){let t=typeVal(r.Type);return t===0?1:(t===1||t===3?(+r.PaidDayUnits||1):0)}
function rowsFor(emp,m=month,y=year){return data.Attendance.filter(r=>r.EmployeeId===emp.Id&&new Date(r.Date).getMonth()+1===m&&new Date(r.Date).getFullYear()===y)}
function salary(emp,rows,m=month,y=year,bonus=true){let s=data.Settings,sd=s.StandardDays>0?s.StandardDays:26,sb=+emp.SalaryBase||8500000,ob=+emp.OvertimeBase||7000000,daily=sb/sd,hour=ob/sd/8,R={PaidDays:0,WorkedDays:0,LeaveDays:0,BasePay:0,DayOtPay:0,NightOtPay:0,NightExtraPay:0,SundayDayPay:0,SundayNightPay:0,AttendanceBonus:0,Insurance:0,UnionFee:0,Gross:0,Net:0};
for(const r of rows){let d=new Date(r.Date),sun=d.getDay()===0,t=typeVal(r.Type),night=shiftVal(r.Shift)==='Night',h=+r.OvertimeHours||0;if(t===1&&!sun){R.LeaveDays+=+r.PaidDayUnits||1;R.PaidDays+=1;continue}if(t===3&&!sun){R.PaidDays+=+r.PaidDayUnits||1;continue}if(t===0){if(!sun){R.WorkedDays++;R.PaidDays++;if(night)R.NightExtraPay+=hour*s.NightExtraHours*s.NightExtraRate;if(h>0){if(night)R.NightOtPay+=hour*(Math.min(h,2)*s.NormalOvertimeRate+Math.max(h-2,0)*s.NightOvertimeAfter2Rate);else R.DayOtPay+=hour*h*s.NormalOvertimeRate}}else{h=h>0?h:s.SundayDefaultHours;if(night)R.SundayNightPay+=hour*h*s.SundayNightRate;else R.SundayDayPay+=hour*h*s.SundayDayRate}}else if(t===2){if(sun){if(night)R.SundayNightPay+=hour*h*s.SundayNightRate;else R.SundayDayPay+=hour*h*s.SundayDayRate}else if(night)R.NightOtPay+=hour*(Math.min(h,2)*s.NormalOvertimeRate+Math.max(h-2,0)*s.NightOvertimeAfter2Rate);else R.DayOtPay+=hour*h*s.NormalOvertimeRate}}
R.BasePay=daily*R.PaidDays;R.AttendanceBonus=bonus?s.AttendanceBonus:0;R.Insurance=sb*s.InsuranceRate;R.UnionFee=sb*s.UnionRate;R.Gross=R.BasePay+R.DayOtPay+R.NightOtPay+R.NightExtraPay+R.SundayDayPay+R.SundayNightPay+R.AttendanceBonus;R.Net=R.Gross-R.Insurance-R.UnionFee;return R}
function applyLeave(){let today=new Date(),day=Math.max(1,Math.min(28,+data.Settings.LeaveAccrualDay||16)),amt=Math.max(0,+data.Settings.LeaveAccrualAmount||0),changed=false;for(const e of data.Employees){if(!e.LastLeaveAccrualDate){e.LastLeaveAccrualDate=today.toISOString();changed=true;continue}let cursor=new Date(e.LastLeaveAccrualDate), m=new Date(cursor.getFullYear(),cursor.getMonth(),1),end=new Date(today.getFullYear(),today.getMonth(),1);while(m<=end){let d=new Date(m.getFullYear(),m.getMonth(),day);if(d>cursor&&d<=today){e.AnnualLeaveBalance=(+e.AnnualLeaveBalance||0)+amt;if(!data.LeaveAccruals.some(a=>a.EmployeeId===e.Id&&isoDate(a.Date)===isoDate(d)))data.LeaveAccruals.push({Id:crypto.randomUUID(),EmployeeId:e.Id,Date:d.toISOString(),Amount:amt,Note:`Tự cộng phép tháng ${m.getMonth()+1}/${m.getFullYear()}`});cursor=d;changed=true}m.setMonth(m.getMonth()+1)}e.LastLeaveAccrualDate=cursor.toISOString()}if(changed)localStorage.setItem('chamcong_data',JSON.stringify(data))}
function renderAll(){if(!data.Employees.find(e=>e.Id===current?.Id))current=data.Employees[0];renderProfile();renderCalendar();renderDay();renderMonth();renderEmployees();renderOT();renderLeave();renderPayroll();renderRules();updateSync()}
function renderProfile(){let initials=current.Name.split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();$('#avatar').textContent=initials;$('#empName').textContent=current.Name;$('#empMeta').textContent=`Mã NV: ${current.Code} • Phép còn: ${+current.AnnualLeaveBalance||0} ngày`;$('#empSalary').textContent=`Lương công ${money(current.SalaryBase)} • OT ${money(current.OvertimeBase)}`;$('#employeeCards').innerHTML=data.Employees.map(e=>`<button class="emp-card ${e.Id===current.Id?'active':''}" data-eid="${e.Id}"><b>${e.Code}</b><br>${e.Name}</button>`).join('');$$('[data-eid]').forEach(b=>b.onclick=()=>{current=data.Employees.find(e=>e.Id===b.dataset.eid);renderAll()})}
function renderCalendar(){let y=calDate.getFullYear(),m=calDate.getMonth();$('#calTitle').textContent=`Tháng ${String(m+1).padStart(2,'0')}/${y}`;let first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset),html='';for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let rs=data.Attendance.filter(r=>r.EmployeeId===current.Id&&isoDate(r.Date)===isoDate(d)),cls=['day'];if(d.getMonth()!==m)cls.push('other');if(d.getDay()===0)cls.push('sunday');if(isoDate(d)===isoDate(selected))cls.push('selected');let dot='';if(rs.some(r=>typeVal(r.Type)===1))dot='<i class="dot leaveDot"></i>';else if(rs.some(r=>typeVal(r.Type)===2||+r.OvertimeHours>0))dot='<i class="dot otdot"></i>';else if(rs.length)dot='<i class="dot"></i>';html+=`<button class="${cls.join(' ')}" data-date="${isoDate(d)}">${d.getDate()}${dot}</button>`}$('#calendarDays').innerHTML=html;$$('.day').forEach(b=>b.onclick=()=>{selected=new Date(b.dataset.date+'T12:00:00');calDate=new Date(selected);renderCalendar();renderDay()})}
function renderDay(){let rs=data.Attendance.filter(r=>r.EmployeeId===current.Id&&isoDate(r.Date)===isoDate(selected));$('#selectedDate').textContent=fmt(selected);$('#detailDate').textContent=fmt(selected)+(selected.getDay()===0?' • Chủ nhật':'');$('#dayDetail').textContent=rs.length?rs.map(r=>`● ${typeName(typeVal(r.Type))} • ${shiftVal(r.Shift)==='Day'?'Ca ngày':'Ca đêm'}\n  Công: ${paid(r)}   OT: ${+r.OvertimeHours||0} giờ`).join('\n\n'):'Chưa có chấm công.\n\nChọn ngày trên lịch để xem chi tiết.'}
function renderMonth(){$('#month').value=month;$('#year').value=year;$('#monthTitle').textContent=`Tổng kết tháng ${String(month).padStart(2,'0')}/${year}`;let rs=rowsFor(current).sort((a,b)=>new Date(b.Date)-new Date(a.Date));$('#attendanceRows').innerHTML=rs.map(r=>`<tr><td>${fmt(r.Date)}</td><td>${typeName(typeVal(r.Type))}</td><td>${shiftVal(r.Shift)==='Day'?'Ngày':'Đêm'}</td><td>${paid(r)}</td><td>${+r.OvertimeHours||0}</td><td>${new Date(r.Date).getDay()===0?'Chủ nhật':r.Note||''}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có dữ liệu.</td></tr>';let s=salary(current,rs,month,year,$('#bonus').checked);let lines=[['Lương công',s.BasePay],['OT ngày',s.DayOtPay],['OT đêm',s.NightOtPay],['Ca đêm +30%',s.NightExtraPay],['Chủ nhật',s.SundayDayPay+s.SundayNightPay],['Chuyên cần',s.AttendanceBonus],['Bảo hiểm',-s.Insurance],['Công đoàn',-s.UnionFee]];$('#salaryLines').innerHTML=lines.map(x=>`<div class="salary-line"><span>${x[0]}</span><strong>${x[1]<0?'− ':''}${money(Math.abs(x[1]))}</strong></div>`).join('');$('#netPay').textContent=money(s.Net)}
function renderEmployees(){
  $('#employeeTable').innerHTML=data.Employees.map(e=>`<tr><td>${e.Code}</td><td><b>${e.Name}</b></td><td>${money(e.SalaryBase)}</td><td>${money(e.OvertimeBase)}</td><td>${+e.AnnualLeaveBalance||0} ngày</td><td><div class="emp-actions"><button class="outline editEmp" data-id="${e.Id}">Sửa</button><button class="outline danger deleteEmp" data-id="${e.Id}">Xóa</button></div></td></tr>`).join('');
  $$('.editEmp').forEach(b=>b.onclick=()=>employeeDialog(data.Employees.find(e=>e.Id===b.dataset.id),false));
  $$('.deleteEmp').forEach(b=>b.onclick=()=>deleteEmployee(b.dataset.id));
}
function deleteEmployee(id){
  const e=data.Employees.find(x=>x.Id===id);if(!e)return;
  if(data.Employees.length<=1)return alert('Cần giữ lại ít nhất 1 nhân viên.');
  const count=data.Attendance.filter(r=>r.EmployeeId===id).length;
  if(!confirm(`Xóa nhân viên ${e.Name} (${e.Code})?\n\nThao tác này sẽ xóa cả ${count} dòng chấm công và lịch sử cộng phép của nhân viên này trên thiết bị.\n\nHãy xuất bản sao lưu JSON trước khi xóa nếu cần giữ lịch sử.`))return;
  data.Employees=data.Employees.filter(x=>x.Id!==id);
  data.Attendance=data.Attendance.filter(x=>x.EmployeeId!==id);
  data.LeaveAccruals=data.LeaveAccruals.filter(x=>x.EmployeeId!==id);
  if(current?.Id===id)current=data.Employees[0];
  saveLocal();
}

function renderOT(){let out=[];for(const e of data.Employees)for(const r of rowsFor(e)){let h=+r.OvertimeHours||0,d=new Date(r.Date),sun=d.getDay()===0,t=typeVal(r.Type),night=shiftVal(r.Shift)==='Night',a=0,b=0,sd=0,sn=0;if(sun&&(t===0||t===2)){h=h||data.Settings.SundayDefaultHours;if(night)sn=h;else sd=h}else if(t===2&&h>0){if(night){a=Math.min(h,2);b=Math.max(h-2,0)}else a=h}else continue;out.push([d,e,r,a,b,sd,sn])}out.sort((a,b)=>b[0]-a[0]);$('#otTable').innerHTML=out.map(x=>`<tr><td>${fmt(x[0])}</td><td>${x[1].Code}</td><td>${x[1].Name}</td><td>${shiftVal(x[2].Shift)==='Day'?'Ngày':'Đêm'}</td><td>${x[3]||''}</td><td>${x[4]||''}</td><td>${x[5]||''}</td><td>${x[6]||''}</td></tr>`).join('')||'<tr><td colspan="8">Chưa có dữ liệu.</td></tr>'}
function renderLeave(){let out=[];for(const e of data.Employees){for(const r of rowsFor(e).filter(r=>typeVal(r.Type)===1))out.push([new Date(r.Date),e,'Nghỉ phép',`-${+r.PaidDayUnits||1} ngày`,r.Note||'']);for(const a of data.LeaveAccruals.filter(a=>a.EmployeeId===e.Id&&new Date(a.Date).getMonth()+1===month&&new Date(a.Date).getFullYear()===year))out.push([new Date(a.Date),e,'Cộng phép',`+${a.Amount} ngày`,a.Note||''])}out.sort((a,b)=>b[0]-a[0]);$('#leaveTable').innerHTML=out.map(x=>`<tr><td>${fmt(x[0])}</td><td>${x[1].Code}</td><td>${x[1].Name}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có dữ liệu.</td></tr>'}
function renderPayroll(){$('#payrollTitle').textContent=`Tháng ${String(month).padStart(2,'0')}/${year}`;$('#payrollTable').innerHTML=data.Employees.map(e=>{let s=salary(e,rowsFor(e),month,year,$('#bonus').checked);return `<tr><td>${e.Code}</td><td>${e.Name}</td><td>${s.PaidDays}</td><td class="money">${money(s.BasePay)}</td><td class="money">${money(s.DayOtPay+s.NightOtPay)}</td><td class="money">${money(s.NightExtraPay)}</td><td class="money">${money(s.SundayDayPay+s.SundayNightPay)}</td><td class="money">${money(s.AttendanceBonus)}</td><td class="money">${money(s.Insurance)}</td><td class="money">${money(s.UnionFee)}</td><td class="money"><b>${money(s.Net)}</b></td></tr>`}).join('')}
const rules=[['StandardDays','Công chuẩn'],['AttendanceBonus','Thưởng chuyên cần'],['InsuranceRate','Bảo hiểm (tỷ lệ, VD 0.105)'],['UnionRate','Công đoàn (tỷ lệ)'],['NormalOvertimeRate','OT ngày thường'],['SundayDayRate','Chủ nhật ca ngày'],['SundayNightRate','Chủ nhật ca đêm'],['NightExtraRate','Phụ cấp ca đêm'],['NightOvertimeAfter2Rate','OT đêm sau 2 giờ'],['NightExtraHours','Số giờ phụ cấp đêm'],['SundayDefaultHours','Giờ CN mặc định'],['LeaveAccrualDay','Ngày tự cộng phép'],['LeaveAccrualAmount','Số phép cộng/tháng']];
function renderRules(){$('#ruleFields').innerHTML=rules.map(([k,l])=>`<label class="field"><span>${l}</span><input name="${k}" type="number" step="0.001" value="${data.Settings[k]}"></label>`).join('')}
function showModal(title,body,onOk,ok='Lưu'){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalOk').textContent=ok;let dlg=$('#modal');dlg.showModal();$('#modalForm').onsubmit=e=>{e.preventDefault();if(e.submitter?.value==='cancel'){dlg.close();return}if(onOk()!==false)dlg.close()}}
function addAttendance(kind){let d=new Date(selected),sun=d.getDay()===0,main=data.Attendance.some(r=>r.EmployeeId===current.Id&&isoDate(r.Date)===isoDate(d)&&[0,1,3].includes(typeVal(r.Type))),shift=$('input[name=shift]:checked').value;if(kind!=='ot'&&main)return alert('Ngày này đã có dữ liệu công/nghỉ.');if(kind==='leave'){if(sun)return alert('Chủ nhật không cần chấm nghỉ phép.');showModal('Nghỉ phép','<label>Số ngày phép<input id="leaveUnits" type="number" min="0.5" step="0.5" value="1"></label>',()=>{let u=+$('#leaveUnits').value;if(!u||current.AnnualLeaveBalance<u)return alert(`Không đủ phép năm. Hiện còn ${current.AnnualLeaveBalance||0} ngày.`),false;current.AnnualLeaveBalance-=u;data.Attendance.push({Id:crypto.randomUUID(),EmployeeId:current.Id,Date:d.toISOString(),Type:1,Shift:shift,OvertimeHours:0,PaidDayUnits:u,Note:`Nghỉ phép ${u} ngày`});saveLocal()});return}if(kind==='holiday'){if(sun)return alert('Chủ nhật không tính công.');data.Attendance.push({Id:crypto.randomUUID(),EmployeeId:current.Id,Date:d.toISOString(),Type:3,Shift:shift,OvertimeHours:0,PaidDayUnits:1,Note:'Nghỉ lễ - không trừ phép'});saveLocal();return}if(kind==='work'&&sun||kind==='ot'){showModal(kind==='work'?'Làm Chủ nhật':'Tăng ca',`<label>Số giờ<input id="hours" type="number" min="0.5" step="0.5" value="${kind==='work'?data.Settings.SundayDefaultHours:3}"></label>`,()=>{let h=+$('#hours').value;if(!(h>0))return false;data.Attendance.push({Id:crypto.randomUUID(),EmployeeId:current.Id,Date:d.toISOString(),Type:kind==='work'?0:2,Shift:shift,OvertimeHours:h,PaidDayUnits:1,Note:''});saveLocal()});return}data.Attendance.push({Id:crypto.randomUUID(),EmployeeId:current.Id,Date:d.toISOString(),Type:0,Shift:shift,OvertimeHours:0,PaidDayUnits:1,Note:''});saveLocal()}
function employeeDialog(e,isNew){showModal(isNew?'Thêm nhân viên':'Sửa nhân viên',`<label>Mã nhân viên<input id="ecode" value="${e.Code||''}"></label><label>Tên nhân viên<input id="ename" value="${isNew?'':e.Name||''}"></label><label>Lương tính công<input id="esal" type="number" value="${e.SalaryBase||8500000}"></label><label>Lương tính tăng ca<input id="eot" type="number" value="${e.OvertimeBase||7000000}"></label><label>Phép năm còn lại<input id="eleave" type="number" step="0.5" value="${e.AnnualLeaveBalance||0}"></label>`,()=>{let code=$('#ecode').value.trim(),name=$('#ename').value.trim();if(!code||!name)return alert('Nhập đủ mã và tên.'),false;if(data.Employees.some(x=>x.Id!==e.Id&&x.Code.toLowerCase()===code.toLowerCase()))return alert('Mã nhân viên đã tồn tại.'),false;Object.assign(e,{Code:code,Name:name,SalaryBase:+$('#esal').value,OvertimeBase:+$('#eot').value,AnnualLeaveBalance:+$('#eleave').value});if(isNew)data.Employees.push(e);current=e;saveLocal()})}
function autoPush(){}
function updateSync(){$('#syncState').textContent='Đã lưu trên thiết bị • không cần Internet'}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');renderAll()});
$('#prev').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#next').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#today').onclick=()=>{selected=new Date();calDate=new Date();renderCalendar();renderDay()};$$('[data-action]').forEach(b=>b.onclick=()=>addAttendance(b.dataset.action));$('#deleteBtn').onclick=()=>{let rs=data.Attendance.filter(r=>r.EmployeeId===current.Id&&isoDate(r.Date)===isoDate(selected));if(!rs.length)return alert('Ngày này chưa có dữ liệu.');let r=rs[rs.length-1];if(confirm(`Xóa ${typeName(typeVal(r.Type))} ngày ${fmt(selected)}?`)){if(typeVal(r.Type)===1)current.AnnualLeaveBalance+=(+r.PaidDayUnits||1);data.Attendance=data.Attendance.filter(x=>x.Id!==r.Id);saveLocal()}};
for(let i=1;i<=12;i++)$('#month').add(new Option(i,i));for(let y=new Date().getFullYear()-5;y<=new Date().getFullYear()+5;y++)$('#year').add(new Option(y,y));$('#month').value=month;$('#year').value=year;$('#month').onchange=()=>{month=+$('#month').value;renderAll()};$('#year').onchange=()=>{year=+$('#year').value;renderAll()};$('#bonus').onchange=renderAll;$('#addEmp').onclick=()=>{if(data.Employees.length>=5)return alert('App giới hạn tối đa 5 người.');let e=newEmp();e.Code=`NV${String(data.Employees.length+1).padStart(2,'0')}`;employeeDialog(e,true)};
$('#rulesForm').onsubmit=e=>{e.preventDefault();new FormData(e.target).forEach((v,k)=>data.Settings[k]=+v);saveLocal();alert('Đã lưu quy tắc.')};
$('#exportJson').onclick=()=>download('chamcong-backup.json',JSON.stringify(data,null,2),'application/json');$('#importJson').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let d=JSON.parse(await f.text());data=d;data.Settings={...defaults,...data.Settings};current=data.Employees[0];saveLocal()}catch{alert('File JSON không hợp lệ.')}};
function download(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
/* Legacy CSV export removed */
/* let head=['Ma NV','Nhan vien','Cong','Luong cong','OT','Ca dem','Chu nhat','Chuyen can','Bao hiem','Cong doan','Thuc nhan'],lines=[head.join(',')];for(const e of data.Employees){let s=salary(e,rowsFor(e),month,year,$('#bonus').checked);lines.push([e.Code,`"${e.Name}"`,s.PaidDays,s.BasePay,s.DayOtPay+s.NightOtPay,s.NightExtraPay,s.SundayDayPay+s.SundayNightPay,s.AttendanceBonus,s.Insurance,s.UnionFee,s.Net].join(','))}download(`BangLuong_${month}_${year}.csv`,'\ufeff'+lines.join('\n'),'text/csv;charset=utf-8')}; */

// XLSX native, offline: Office Open XML in a ZIP container (no CSV or CDN).
const xmlEscape=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function zipStore(entries){
 const encoder=new TextEncoder(), chunks=[], central=[];let offset=0;
 const u16=n=>[n&255,(n>>>8)&255],u32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
 const crcTable=zipStore.table||(zipStore.table=Array.from({length:256},(_,n)=>{for(let j=0;j<8;j++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0}));
 const crc32=bytes=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0};
 for(const [name,body] of entries){const nm=encoder.encode(name),bytes=encoder.encode(body),crc=crc32(bytes),size=bytes.length;
 const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(size),...u32(size),...u16(nm.length),...u16(0),...nm]);
 chunks.push(local,bytes);
 central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(size),...u32(size),...u16(nm.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...nm]));
 offset+=local.length+size;
 }
 const centralSize=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(centralSize),...u32(offset),...u16(0)]);
 return new Blob([...chunks,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
function excelCol(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function excelSheet(rows){
 let widths=rows[0].map((_,i)=>Math.min(36,Math.max(12,...rows.slice(0,40).map(r=>String(r[i]??'').length+2))));
 const cols='<cols>'+widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')+'</cols>';
 const body=rows.map((r,i)=>`<row r="${i+1}">`+r.map((v,j)=>{const ref=excelCol(j+1)+(i+1),style=i===0?' s="1"':'';return typeof v==='number'&&Number.isFinite(v)?`<c r="${ref}"${style}><v>${v}</v></c>`:`<c r="${ref}" t="inlineStr"${style}><is><t>${xmlEscape(v)}</t></is></c>`}).join('')+'</row>').join('');
 return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="18"/>${cols}<sheetData>${body}</sheetData></worksheet>`;
}
function exportExcel(){
 const heads=['Mã NV','Nhân viên','Công hưởng lương','Lương công','Tăng ca','Phụ cấp ca đêm','Chủ nhật','Chuyên cần','Bảo hiểm','Công đoàn','Thực nhận'];
 const payroll=[heads],attend=[['Ngày','Mã NV','Nhân viên','Loại','Ca','Công','OT (giờ)','Ghi chú']],leave=[['Ngày','Mã NV','Nhân viên','Loại','Số ngày','Ghi chú']];
 for(const e of data.Employees){
  const records=rowsFor(e),v=salary(e,records,month,year,$('#bonus').checked);
  payroll.push([e.Code,e.Name,+v.PaidDays,+v.BasePay,+(v.DayOtPay+v.NightOtPay),+v.NightExtraPay,+(v.SundayDayPay+v.SundayNightPay),+v.AttendanceBonus,+v.Insurance,+v.UnionFee,+v.Net]);
  for(const r of records)attend.push([fmt(new Date(r.Date)),e.Code,e.Name,typeName(typeVal(r.Type)),shiftVal(r.Shift)==='Day'?'Ngày':'Đêm',+paid(r),+r.OvertimeHours||0,r.Note||'']);
  for(const r of data.LeaveAccruals.filter(r=>r.EmployeeId===e.Id&&new Date(r.Date).getMonth()+1===month&&new Date(r.Date).getFullYear()===year))leave.push([fmt(new Date(r.Date)),e.Code,e.Name,'Cộng phép',+r.Amount,r.Note||'']);
  for(const r of records.filter(r=>typeVal(r.Type)===1))leave.push([fmt(new Date(r.Date)),e.Code,e.Name,'Nghỉ phép',-(+r.PaidDayUnits||1),r.Note||'']);
 }
 attend.splice(1,attend.length-1,...attend.slice(1).sort((a,b)=>a[0].split('/').reverse().join('').localeCompare(b[0].split('/').reverse().join(''))));
 const names=['Bảng lương','Chấm công','Nghỉ phép'],tables=[payroll,attend,leave];
 const files=[
 ['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${names.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],
 ['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
 ['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((n,i)=>`<sheet name="${n}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],
 ['xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${names.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],
 ['xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF126552"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>']
 ];
 tables.forEach((t,i)=>files.push([`xl/worksheets/sheet${i+1}.xml`,excelSheet(t)]));
 const blob=zipStore(files),url=URL.createObjectURL(blob),a=document.createElement('a');
 a.href=url;a.download=`BangLuong_${String(month).padStart(2,'0')}_${year}.xlsx`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
$('#exportExcel').onclick=exportExcel;

setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('vi-VN'),1000);$('#clock').textContent=new Date().toLocaleTimeString('vi-VN');applyLeave();renderAll();updateSync();
